=== 30s/qcadoo/qcadoo-maven-plugin/src/main/java/model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/model" xmlns="http://www.qcadoo.com/model" elementFormDefault="qualified">

	<xsd:element name="model">
		
        <xsd:complexType>
			<xsd:sequence>
				<xsd:element name="fields" type="fieldsType" minOccurs="1" maxOccurs="1" />
				<xsd:element name="hooks" type="hooksType" minOccurs="1" maxOccurs="1" />
				<xsd:element name="identifier" type="identifierExpressionType" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="name" type="identifierType" use="required" />
			<xsd:attribute name="plugin" type="identifierType" use="optional" />
			<xsd:attribute name="deletable" type="xs:boolean" />
			<xsd:attribute name="insertable" type="xs:boolean" />
			<xsd:attribute name="updatable" type="xs:boolean" />
		</xsd:complexType>
    </xsd:element>

	<xsd:complexType name="hooksType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="validatesWith" type="hookType" />
			<xsd:element name="onSave" type="hookType" />
			<xsd:element name="onUpdate" type="hookType" />
			<xsd:element name="onCreate" type="hookType" />
			<xsd:element name="onCopy" type="hookType" />
			<xsd:element name="onView" type="hookType" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="fieldsType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="integer" type="fieldType" />
			<xsd:element name="string" type="stringFieldType" />
			<xsd:element name="text" type="fieldType" />
			<xsd:element name="decimal" type="fieldType" />
			<xsd:element name="datetime" type="fieldType" />
			<xsd:element name="date" type="fieldType" />
			<xsd:element name="boolean" type="fieldType" />
			<xsd:element name="belongsTo" type="belongsToFieldType" />
			<xsd:element name="hasMany" type="hasManyFieldType" />
			<xsd:element name="tree" type="treeFieldType" />
			<xsd:element name="enum" type="enumFieldType" />
			<xsd:element name="dictionary" type="dictionaryFieldType" />
			<xsd:element name="password" type="fieldType" />
			<xsd:element name="priority" type="priorityFieldType" minOccurs="0" maxOccurs="1" />
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="identifierExpressionType">
		<xsd:attribute name="expression" type="xs:string" />
	</xsd:complexType>
	
	<xsd:complexType name="validatesType">
		<xsd:attribute name="message" type="xs:string" />
	</xsd:complexType>

	<xsd:complexType name="validatesLengthType">
		<xsd:complexContent>
			<xsd:extension base="validatesType">
				<xsd:attribute name="min" type="xs:integer" />
				<xsd:attribute name="is" type="xs:integer" />
				<xsd:attribute name="max" type="xs:integer" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="validatesRangeType">
		<xsd:complexContent>
			<xsd:extension base="validatesType">
				<xsd:attribute name="from" type="xs:string" />
				<xsd:attribute name="to" type="xs:string" />
				<xsd:attribute name="exclusively" type="xs:boolean" default="false" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="validatesRegexType">
		<xsd:complexContent>
			<xsd:extension base="validatesType">
				<xsd:attribute name="pattern" type="xs:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="hookType">
		<xsd:attribute name="class" type="classType" use="required" />
		<xsd:attribute name="method" type="identifierType" use="required" />
	</xsd:complexType>

	<xsd:complexType name="fieldType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="validatesWith" type="hookType" />
			<xsd:element name="validatesLength" type="validatesLengthType" />
			<xsd:element name="validatesPrecision" type="validatesLengthType" />
			<xsd:element name="validatesScale" type="validatesLengthType" />
			<xsd:element name="validatesRange" type="validatesRangeType" />
			<xsd:element name="validatesRegex" type="validatesRegexType" />
		</xsd:choice>
		<xsd:attribute name="name" type="identifierType" use="required" />
		<xsd:attribute name="default" type="xs:string" />
		<xsd:attribute name="readonly" type="xs:boolean" default="false" />
		<xsd:attribute name="persistent" type="xs:boolean" default="true" />
		<xsd:attribute name="required" type="xs:boolean" default="false" />
		<xsd:attribute name="unique" type="xs:boolean" default="false" />
	</xsd:complexType>

	<xsd:complexType name="stringFieldType">
		<xsd:complexContent>
			<xsd:extension base="fieldType">
				<xsd:attribute name="expression" type="xs:string" use="optional" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="belongsToFieldType">
		<xsd:complexContent>
			<xsd:extension base="fieldType">
				<xsd:attribute name="model" type="identifierType" use="required" />
				<xsd:attribute name="plugin" type="identifierType" />
				<xsd:attribute name="lazy" type="xs:boolean" default="true" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="hasManyFieldType">
		<xsd:complexContent>
			<xsd:extension base="fieldType">
				<xsd:attribute name="model" type="identifierType" use="required" />
				<xsd:attribute name="plugin" type="identifierType" />
				<xsd:attribute name="joinField" type="identifierType" use="required" />
				<xsd:attribute name="cascade" type="cascadeType" default="none" />
				<xsd:attribute name="copyable" type="xs:boolean" default="false" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="treeFieldType">
		<xsd:complexContent>
			<xsd:extension base="fieldType">
				<xsd:attribute name="model" type="identifierType" use="required" />
				<xsd:attribute name="plugin" type="identifierType" />
				<xsd:attribute name="joinField" type="identifierType" use="required" />
				<xsd:attribute name="cascade" type="cascadeType" default="none" />
				<xsd:attribute name="copyable" type="xs:boolean" default="false" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="dictionaryFieldType">
		<xsd:complexContent>
			<xsd:extension base="fieldType">
				<xsd:attribute name="plugin" type="identifierType" use="optional" />
				<xsd:attribute name="dictionary" type="identifierType" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="enumFieldType">
		<xsd:complexContent>
			<xsd:extension base="fieldType">
				<xsd:attribute name="values" use="required">
					<xsd:simpleType>
						<xsd:restriction base="xs:string">
							<xsd:pattern value="[a-zA-Z0-9]*(,[a-zA-Z0-9]*)*" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="priorityFieldType">
		<xsd:attribute name="name" type="identifierType" use="required" />
		<xsd:attribute name="scope" type="identifierType" use="optional" />
	</xsd:complexType>

	<xsd:simpleType name="cascadeType">
		<xsd:restriction base="xs:string">
			<xsd:enumeration value="delete" />
			<xsd:enumeration value="none" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="deletableType">
		<xsd:restriction base="xs:string">
			<xsd:enumeration value="false" />
			<xsd:enumeration value="true" />
			<xsd:enumeration value="soft" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="identifierType">
		<xsd:restriction base="xs:string">
			<xsd:pattern value="[a-z][a-zA-Z0-9]*" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="classType">
		<xsd:restriction base="xs:string">
			<xsd:pattern value="[a-z][a-zA-Z0-9.]*.[a-zA-Z0-9]+" />
		</xsd:restriction>
	</xsd:simpleType>

<xsd:schema></xsd:schema>

=== 30s/qcadoo/qcadoo-security/src/main/resources/qcadooSecurity/model/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.1.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<string name="userName" required="true" unique="true">
			<validatesRegex pattern="^[a-zA-Z0-9\\.]+$"
				message="qcadooSecurity.validate.global.error.loginIllegalCharacters" />
		</string>
		<enum name="role" values="" required="true"/>
		<string name="email" />
		<string name="firstName" />
		<string name="lastName" />
		<boolean name="enabled" default="true" />
		<string name="description">
			<validatesLength max="255" />
		</string>
		<password name="password" /><!-- TODO validatesPresenceOnCreate -->
		<password name="passwordConfirmation" persistent="false" /><!-- 
			TODO validatesPresenceOnCreate -->
		<password name="oldPassword" persistent="false" />
		<string name="viewIdentifier" persistent="false" />
		<datetime name="lastActivity" />
	</fields>
	<hooks>
		<validatesWith class="com.qcadoo.security.internal.validators.PasswordValidationService"
			method="checkPassword" />
	</hooks>
	<identifier expression="#userName" />
</model>

=== 30s/qcadoo/qcadoo-model/src/main/resources/qcadooModel/model/unitConversionItem.xml
<?xml version="1.0" encoding="UTF-8"?>
<model name="unitConversionItem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<decimal name="quantityFrom" required="true" />
		<decimal name="quantityTo" required="true"/>
		<dictionary name="unitFrom" dictionary="units" required="true"/>
		<dictionary name="unitTo" dictionary="units" required="true"/>
		<belongsTo name="globalUnitConversionsAggregate" model="globalUnitConversionsAggregate"/>
	</fields>
	<hooks>
		<validatesWith class="com.qcadoo.model.internal.units.hooks.UnitConversionItemValidators" method="validateQuantityFrom"/>	
	</hooks>
</model>
